package org.example.recurring;

import org.example.Task;

import java.time.Instant;

/**
 * A task that repeats on a regular schedule.
 *
 * <p>A {@code RecurringTask} is the template/definition of the recurrence.
 * Concrete occurrences are generated by {@link RecurringTaskExpander}.
 */
public class RecurringTask extends Task {

    private final RecurrencePattern recurrencePattern;
    private final Instant recurrenceEndDate;

    /**
     * Creates a recurring task with no end date (repeats indefinitely).
     *
     * @param id               unique identifier
     * @param title            task title
     * @param description      task description
     * @param owner            task owner name
     * @param startDate        date of the first occurrence
     * @param recurrencePattern how often the task repeats
     */
    public RecurringTask(String id, String title, String description, String owner,
                         Instant startDate, RecurrencePattern recurrencePattern) {
        this(id, title, description, owner, startDate, null, recurrencePattern, null);
    }

    /**
     * Creates a recurring task with a defined recurrence end date.
     *
     * @param id                unique identifier
     * @param title             task title
     * @param description       task description
     * @param owner             task owner name
     * @param startDate         date of the first occurrence
     * @param endDate           end date of each individual occurrence (duration)
     * @param recurrencePattern how often the task repeats
     * @param recurrenceEndDate the date after which no new occurrences are generated;
     *                          {@code null} means indefinitely
     */
    public RecurringTask(String id, String title, String description, String owner,
                         Instant startDate, Instant endDate,
                         RecurrencePattern recurrencePattern, Instant recurrenceEndDate) {
        super(id, title, description, owner, startDate, endDate == null ? startDate : endDate);
        if (recurrencePattern == null) {
            throw new IllegalArgumentException("recurrencePattern must not be null");
        }
        this.recurrencePattern = recurrencePattern;
        this.recurrenceEndDate = recurrenceEndDate;
    }

    /**
     * Returns the recurrence pattern (e.g. WEEKLY, MONTHLY).
     *
     * @return the recurrence pattern
     */
    public RecurrencePattern getRecurrencePattern() {
        return recurrencePattern;
    }

    /**
     * Returns the date after which no new occurrences should be generated,
     * or {@code null} if the task repeats indefinitely.
     *
     * @return the recurrence end date, or {@code null}
     */
    public Instant getRecurrenceEndDate() {
        return recurrenceEndDate;
    }
}